#ifndef SDRSRC_H
#define SDRSRC_H

#include "src/equation_systems/sdr/SDRSource.H"

namespace kynema_sgf::pde::tke {

/** Source terms for SDR equation
 *   \ingroup turb_model
 *
 *  Works for all SDR equations with source term
 */
class SDRSrc : public SDRSource::Register<SDRSrc>
{
public:
    static std::string identifier() { return "SDRSrc"; }

    explicit SDRSrc(const CFDSim& /*sim*/);

    ~SDRSrc() override;

    void operator()(
        int lev, FieldState fstate, amrex::MultiFab& src_term) const override;

private:
    Field& m_sdr_src;
    Field& m_sdr_diss;
};

} // namespace kynema_sgf::pde::tke

#endif /* SDRSRC_H */
