#ifndef PERTURBATIONFORCING_H
#define PERTURBATIONFORCING_H

#include "src/equation_systems/temperature/TemperatureSource.H"
#include "src/core/SimTime.H"
#include "src/CFDSim.H"
#include "src/transport_models/TransportModel.H"
#include "AMReX_REAL.H"

using namespace amrex::literals;

namespace kynema_sgf::pde::temperature {

class PerturbationForcing
    : public TemperatureSource::Register<PerturbationForcing>
{
public:
    static std::string identifier() { return "PerturbationForcing"; }

    explicit PerturbationForcing(const CFDSim& sim);

    ~PerturbationForcing() override;

    void operator()(
        int lev, FieldState fstate, amrex::MultiFab& src_term) const override;

private:
    const CFDSim& m_sim;
    const SimTime& m_time;
    const amrex::AmrCore& m_mesh;
    amrex::Vector<amrex::Real> m_start;
    amrex::Vector<amrex::Real> m_end;
    int m_time_index{100};
    int m_start_level{0};
    amrex::Real m_pert_amplitude{1.0_rt};
};

} // namespace kynema_sgf::pde::temperature
#endif
