#ifndef ACTUATORFORCING_H
#define ACTUATORFORCING_H

#include "src/equation_systems/icns/MomentumSource.H"
#include "src/core/SimTime.H"

namespace kynema_sgf::pde::icns {

/** Body forces introduced by turbines modeled as actuators in flow field.
 *
 *  \ingroup icns_src actuator
 *
 *  \sa Acuator
 */
class ActuatorForcing : public MomentumSource::Register<ActuatorForcing>
{
public:
    static std::string identifier() { return "ActuatorForcing"; }

    explicit ActuatorForcing(const CFDSim& sim);

    ~ActuatorForcing() override;

    void operator()(
        int lev, FieldState fstate, amrex::MultiFab& src_term) const override;

private:
    const Field& m_act_src;
};

} // namespace kynema_sgf::pde::icns

#endif /* ACTUATORFORCING_H */
