#ifndef DENSITYBUOYANCY_H
#define DENSITYBUOYANCY_H

#include "src/core/FieldRepo.H"
#include "src/equation_systems/icns/MomentumSource.H"
#include "AMReX_REAL.H"

using namespace amrex::literals;

namespace kynema_sgf::pde::icns {

/** Buoyancy term from density variations
 *  \ingroup icns_src
 *
 *  \sa RayleighTaylor
 */
class DensityBuoyancy : public MomentumSource::Register<DensityBuoyancy>
{
public:
    static std::string identifier() { return "DensityBuoyancy"; }

    explicit DensityBuoyancy(const CFDSim& sim);

    ~DensityBuoyancy() override;

    void operator()(
        int lev, FieldState fstate, amrex::MultiFab& src_term) const override;

private:
    amrex::Vector<amrex::Real> m_gravity{0.0_rt, 0.0_rt, -9.81_rt};

    amrex::Real m_rho_0{1.0_rt};

    Field& m_density;
};

} // namespace kynema_sgf::pde::icns

#endif /* DensityBuoyancy_H */
