#ifndef FORESTFORCING_H
#define FORESTFORCING_H

#include "src/equation_systems/icns/MomentumSource.H"
#include "src/core/SimTime.H"
#include "src/CFDSim.H"

namespace kynema_sgf::pde::icns {

/** Adds a forcing term to represent forest terrain
 *
 *  \ingroup icns_src
 *
 *
 */
class ForestForcing : public MomentumSource::Register<ForestForcing>
{
public:
    static std::string identifier() { return "ForestForcing"; }

    explicit ForestForcing(const CFDSim& sim);

    ~ForestForcing() override;

    void operator()(
        int lev, FieldState fstate, amrex::MultiFab& src_term) const override;

private:
    const CFDSim& m_sim;
    const Field& m_velocity;
};

} // namespace kynema_sgf::pde::icns

#endif
