#ifndef NONLINEARSGSTERM_H
#define NONLINEARSGSTERM_H

#include "src/equation_systems/icns/MomentumSource.H"
#include "src/core/SimTime.H"

namespace kynema_sgf::pde::icns {

/** Adds the non-linear terms from the Kosovic Model to Momentum Equation..
 *
 *  \ingroup icns_src NonLinearSGS
 *
 *  \sa NonLinearSGS
 */
class NonLinearSGSTerm : public MomentumSource::Register<NonLinearSGSTerm>
{
public:
    static std::string identifier() { return "NonLinearSGSTerm"; }

    explicit NonLinearSGSTerm(const CFDSim& sim);

    ~NonLinearSGSTerm() override;

    void operator()(
        int lev, FieldState fstate, amrex::MultiFab& src_term) const override;

private:
    const Field& m_divNij;
};

} // namespace kynema_sgf::pde::icns

#endif /* NONLINEARSGSTERM_H */
