#ifndef VELOCITYFREEATMOSPHEREFORCING_H
#define VELOCITYFREEATMOSPHEREFORCING_H

#include "src/equation_systems/icns/MomentumSource.H"
#include "src/core/SimTime.H"
#include "src/CFDSim.H"

namespace kynema_sgf::pde::icns {

class VelocityFreeAtmosphereForcing
    : public MomentumSource::Register<VelocityFreeAtmosphereForcing>
{
public:
    static std::string identifier() { return "VelocityFreeAtmosphereForcing"; }

    explicit VelocityFreeAtmosphereForcing(const CFDSim& sim);

    ~VelocityFreeAtmosphereForcing() override;

    void operator()(
        int lev, FieldState fstate, amrex::MultiFab& src_term) const override;

private:
    const SimTime& m_time;
    const amrex::AmrCore& m_mesh;
    std::string m_1d_rans_filename;
    const Field& m_velocity;
    amrex::Vector<amrex::Real> m_wind_heights;
    amrex::Vector<amrex::Real> m_u_values;
    amrex::Vector<amrex::Real> m_v_values;
    amrex::Vector<amrex::Real> m_w_values;
    amrex::Gpu::DeviceVector<amrex::Real> m_wind_heights_d;
    amrex::Gpu::DeviceVector<amrex::Real> m_u_values_d;
    amrex::Gpu::DeviceVector<amrex::Real> m_v_values_d;
    amrex::Gpu::DeviceVector<amrex::Real> m_w_values_d;
    amrex::Real m_meso_start{1.0e30_rt};
    amrex::Real m_meso_timescale{30.0_rt};
    const CFDSim& m_sim;
};

} // namespace kynema_sgf::pde::icns
#endif
